services:
  backend:
    build:
      context: backend
      target: dev-envs
    ports:
      - 8080:8080
    environment:
      - POSTGRES_DB=db_dio
    networks:
      - spring-postgres
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  db:
    image: postgres
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - spring-postgres
    environment:
      - POSTGRES_USER=db_dio_user
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_password
    expose:
      - 5432
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres: